# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension EditorConfig.EditorConfig
code --install-extension James-Yu.latex-workshop
code --install-extension JHeilingbrunner.vscode-gnupg-tool
code --install-extension julialang.language-julia
code --install-extension matklad.rust-analyzer
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension octref.vetur
code --install-extension oijaz.unicode-latex
code --install-extension shuworks.vscode-table-formatter
code --install-extension slevesque.vscode-hexdump
code --install-extension stkb.rewrap
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wmaurer.change-case
code --install-extension wmaurer.html2jade
code --install-extension wwm.better-align
