#!/usr/bin/pkexec /usr/bin/zsh
set -x

# clean up before backing up
pacman -Sc
journalctl --vacuum-time=7d
rm /var/lib/systemd/coredump/*

# backup based on last previous one to save disk space
TARGET=/run/media/ylxdzsw/DATA/pc
NOW=$(date +%y-%m-%d)
LAST=$(tail -n 1 <(sort <(ls $TARGET)))
EX=("/dev/*" "/proc/*" "/sys/*" "/tmp/*" "/run/*" "/mnt/*" /home/ylxdzsw/.cache)
rsync -aAX --info=progress2 --exclude=$^EX --link-dest="$TARGET/$LAST" / "$TARGET/$NOW"